---
title: "21-map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,tidyr,arrow,leaflet,maps,ggplot2,ggrepel,usmap,usdata,feather,tigris,leaflet,sf)
```

# Load data from feather

```{r}
df_ocr_lookup <- read_feather("data/OCR-transformed/2017/ocr_2017_lookup.feather")
df_ocr_long <- read_feather("data/OCR-transformed/2017/ocr_2017_long.feather")
df_ocr_wide <- read_feather("data/OCR-transformed/2017/ocr_2017_wide.feather")

```



```{r}
### Calculate the subpopulation enrollment percentages using the wide data set
subpopulation_enr_percentage<- function(df_ocr_wide) {
  df_ocr_wide<- transform(df_ocr_wide, 
                        HI_ENR_PERCENTAGE = round((SCH_ENR_HI_M+SCH_ENR_HI_F)/(TOT_ENR_M+TOT_ENR_F),2),
                        AM_ENR_PERCENTAGE = round((SCH_ENR_AM_M+SCH_ENR_AM_F)/(TOT_ENR_M+TOT_ENR_F),2),
                        AS_ENR_PERCENTAGE = round((SCH_ENR_AS_M+SCH_ENR_AS_F)/(TOT_ENR_M+TOT_ENR_F),2),
                        HP_ENR_PERCENTAGE = round((SCH_ENR_HP_M+SCH_ENR_HP_F)/(TOT_ENR_M+TOT_ENR_F),2),
                        BL_ENR_PERCENTAGE = round((SCH_ENR_BL_M+SCH_ENR_BL_F)/(TOT_ENR_M+TOT_ENR_F),2),
                        WH_ENR_PERCENTAGE = round((SCH_ENR_WH_M+SCH_ENR_WH_F)/(TOT_ENR_M+TOT_ENR_F),2),
                        TR_ENR_PERCENTAGE = round((SCH_ENR_TR_M+SCH_ENR_TR_F)/(TOT_ENR_M+TOT_ENR_F),2))

  return(df_ocr_wide)
}
```

```{r}
### Calculate the subpopulation gifted and talented enrollment percentages using the wide data set
subpopulation_gtenr_percentage<- function(df_ocr_wide) {
  df_ocr_wide<- transform(df_ocr_wide, 
                        HI_GTENR_PERCENTAGE= round((SCH_GTENR_HI_M+SCH_GTENR_HI_F)/(TOT_GTENR_M+TOT_GTENR_F),2),
                        AM_GTENR_PERCENTAGE = round((SCH_GTENR_AM_M+SCH_GTENR_AM_F)/(TOT_GTENR_M+TOT_GTENR_F),2),
                        AS_GTENR_PERCENTAGE = round((SCH_GTENR_AS_M+SCH_GTENR_AS_F)/(TOT_GTENR_M+TOT_GTENR_F),2),
                        HP_GTENR_PERCENTAGE = round((SCH_GTENR_HP_M+SCH_GTENR_HP_F)/(TOT_GTENR_M+TOT_GTENR_F),2),
                        BL_GTENR_PERCENTAGE = round((SCH_GTENR_BL_M+SCH_GTENR_BL_F)/(TOT_GTENR_M+TOT_GTENR_F),2),
                        WH_GTENR_PERCENTAGE = round((SCH_GTENR_WH_M+SCH_GTENR_WH_F)/(TOT_GTENR_M+TOT_GTENR_F),2),
                        TR_GTENR_PERCENTAGE = round((SCH_GTENR_TR_M+SCH_GTENR_TR_F)/(TOT_GTENR_M+TOT_GTENR_F),2))

  return(df_ocr_wide)
}
```

```{r}
### Calculate the subpopulation gifted and talented enrollment total
subpopulation_gtenr_tot<- function(df_ocr_wide) {
  df_ocr_wide<- transform(df_ocr_wide, 
                        HI_GTENR=  SCH_GTENR_HI_M+SCH_GTENR_HI_F,
                        AM_GTENR = SCH_GTENR_AM_M+SCH_GTENR_AM_F,
                        AS_GTENR = SCH_GTENR_AS_M+SCH_GTENR_AS_F,
                        HP_GTENR = SCH_GTENR_HP_M+SCH_GTENR_HP_F,
                        BL_GTENR = SCH_GTENR_BL_M+SCH_GTENR_BL_F,
                        WH_GTENR = SCH_GTENR_WH_M+SCH_GTENR_WH_F,
                        TR_GTENR = SCH_GTENR_TR_M+SCH_GTENR_TR_F)

  return(df_ocr_wide)
}
```

```{r}
### Calculate the subpopulation enrollment total
subpopulation_enr_tot<- function(df_ocr_wide) {
  df_ocr_wide<- transform(df_ocr_wide, 
                        HI_ENR=  SCH_ENR_HI_M+SCH_ENR_HI_F,
                        AM_ENR = SCH_ENR_AM_M+SCH_ENR_AM_F,
                        AS_ENR = SCH_ENR_AS_M+SCH_ENR_AS_F,
                        HP_ENR = SCH_ENR_HP_M+SCH_ENR_HP_F,
                        BL_ENR = SCH_ENR_BL_M+SCH_ENR_BL_F,
                        WH_ENR = SCH_ENR_WH_M+SCH_ENR_WH_F,
                        TR_ENR = SCH_ENR_TR_M+SCH_ENR_TR_F)

  return(df_ocr_wide)
}
```

```{r}
### Calculate the subpopulation representation index % of GT/ % of ENR (call this function aftr the enrollment and GT enrollment percentages are calculated)

subpopulation_representation_index<- function(df_ocr_wide) {
   df_ocr_wide<- transform(df_ocr_wide, 
                        HI_REP_INDEX = HI_GTENR_PERCENTAGE/HI_ENR_PERCENTAGE,
                        AM_REP_INDEX = AM_GTENR_PERCENTAGE/AM_ENR_PERCENTAGE,
                        AS_REP_INDEX = HI_GTENR_PERCENTAGE/HI_ENR_PERCENTAGE,
                        HP_REP_INDEX = HP_GTENR_PERCENTAGE/HP_ENR_PERCENTAGE,
                        BL_REP_INDEX = BL_GTENR_PERCENTAGE/BL_ENR_PERCENTAGE,
                        WH_REP_INDEX = WH_GTENR_PERCENTAGE/WH_ENR_PERCENTAGE,
                        TR_REP_INDEX = TR_GTENR_PERCENTAGE/TR_ENR_PERCENTAGE)
   
  return(df_ocr_wide)
}


```



```{r}
subpopulation_main <- function(df_ocr_wide) {
          df_ocr_wide <-  df_ocr_wide %>% 
                                          subpopulation_enr_percentage(.) %>%
                                          subpopulation_gtenr_percentage(.) %>%
                                          subpopulation_enr_tot(.) %>%
                                          subpopulation_gtenr_tot(.) %>%
                                          subpopulation_representation_index (.)
          return(df_ocr_wide)
}
```

```{r}
## Source subpop functions
source(knitr::purl("12-subpopulation_function.Rmd", output = tempfile()))
# source(knitr::purl("13-enrollment-fixing-functions-for-long-data.Rmd", output = tempfile()))
# source(knitr::purl("14-enrollment-fixing-functions-for-wide-data.Rmd", output = tempfile()))

## Generate subpop aggregations & state abbreviations
df_states_nolocale <- subpopulation_gentable(df_ocr_wide, groupby_colnames = c('LEA_STATE','TITLEI'))
df_states_nolocale$state<-abbr2state(df_states_nolocale$LEA_STATE)

## Bin REP INDEX by grade (see p.104+ in Access Denied report)
df_states_nolocale[, paste0(grep("INDEX", names(df_states_nolocale), value = TRUE),"_GRADE")] <- 
  lapply(df_states_nolocale[, grepl("INDEX", names(df_states_nolocale))], 
         function(x) cut(x,
                         breaks = c(-Inf, 0.8, 0.85, 0.9, 0.95, Inf),
                         labels = c("F","D","C","B","A")))

## Add regional designation
regions <- vroom("data/regions.csv")
df_states_nolocale <- merge(df_states_nolocale, regions, by = "LEA_STATE")
  
```

```{r}

#Regional representation index on US map (example -- TBI with ShinyApp)
plot_usmap(data = df_states_nolocale,
           values = "HI_REP_INDEX", 
           color = "black",
           include = df_states_nolocale$LEA_STATE[df_states_nolocale$REGION == "Pacific"]) + 
 scale_fill_continuous(
    low = "white", 
    high = "blue", 
    name = "HI REPRESENTATION INDEX", 
    label = scales::comma) + 
  theme(legend.position = "right")

#TitleI representation index on US Map 
plot_usmap(data = df_states_nolocale, 
           values = "HI_REP_INDEX", 
           color = "black") + 
 scale_fill_continuous(
    low = "white", 
    high = "blue", 
    name = "HI REPRESENTATION INDEX", 
    label = scales::comma) + 
  theme(legend.position = "right")

plot_usmap(data = df_ocr_stateTitleI, 
           values = "BL_REP_INDEX", 
           color = "black") + 
 scale_fill_continuous(
    low = "white", 
    high = "blue", 
    name = "BL REPRESENTATION INDEX", 
    label = scales::comma) + 
  theme(legend.position = "right")

plot_usmap(data = df_ocr_stateTitleI, values = "WH_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "WH REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateTitleI, values = "AM_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "AM REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateTitleI, values = "AS_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "AS REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateTitleI, values = "TR_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "TR REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")
```
```{r}
#NoTitleI representation index on US Map 
plot_usmap(data = df_ocr_stateNoTitleI, values = "HI_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "HI REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateNoTitleI, values = "BL_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "BL REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateNoTitleI, values = "WH_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "WH REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateNoTitleI, values = "AM_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "AM REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateNoTitleI, values = "AS_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "AS REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")

plot_usmap(data = df_ocr_stateNoTitleI, values = "TR_REP_INDEX", color = "black") + 
 scale_fill_continuous(
    low = "white", high = "blue", name = "TR REPRESENTATION INDEX", label = scales::comma
  ) + theme(legend.position = "right")
```